(cl:defpackage typepyt-msg
  (:use )
  (:export
   "<ARMJOINTANGLESACTION>"
   "ARMJOINTANGLESACTION"
   "<ARMJOINTANGLESACTIONFEEDBACK>"
   "ARMJOINTANGLESACTIONFEEDBACK"
   "<ARMJOINTANGLESACTIONGOAL>"
   "ARMJOINTANGLESACTIONGOAL"
   "<ARMJOINTANGLESACTIONRESULT>"
   "ARMJOINTANGLESACTIONRESULT"
   "<ARMJOINTANGLESFEEDBACK>"
   "ARMJOINTANGLESFEEDBACK"
   "<ARMJOINTANGLESGOAL>"
   "ARMJOINTANGLESGOAL"
   "<ARMJOINTANGLESRESULT>"
   "ARMJOINTANGLESRESULT"
   "<JOINTANGLES>"
   "JOINTANGLES"
  ))

