; Auto-generated. Do not edit!


(cl:in-package typepyt-msg)


;//! \htmlinclude ArmJointAnglesGoal.msg.html

(cl:defclass <ArmJointAnglesGoal> (roslisp-msg-protocol:ros-message)
  ((angles
    :reader angles
    :initarg :angles
    :type typepyt-msg:JointAngles
    :initform (cl:make-instance 'typepyt-msg:JointAngles)))
)

(cl:defclass ArmJointAnglesGoal (<ArmJointAnglesGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ArmJointAnglesGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ArmJointAnglesGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name typepyt-msg:<ArmJointAnglesGoal> is deprecated: use typepyt-msg:ArmJointAnglesGoal instead.")))

(cl:ensure-generic-function 'angles-val :lambda-list '(m))
(cl:defmethod angles-val ((m <ArmJointAnglesGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader typepyt-msg:angles-val is deprecated.  Use typepyt-msg:angles instead.")
  (angles m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ArmJointAnglesGoal>) ostream)
  "Serializes a message object of type '<ArmJointAnglesGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'angles) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ArmJointAnglesGoal>) istream)
  "Deserializes a message object of type '<ArmJointAnglesGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'angles) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ArmJointAnglesGoal>)))
  "Returns string type for a message object of type '<ArmJointAnglesGoal>"
  "typepyt/ArmJointAnglesGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ArmJointAnglesGoal)))
  "Returns string type for a message object of type 'ArmJointAnglesGoal"
  "typepyt/ArmJointAnglesGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ArmJointAnglesGoal>)))
  "Returns md5sum for a message object of type '<ArmJointAnglesGoal>"
  "2b177ebe4b350b7b614560d610addf92")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ArmJointAnglesGoal)))
  "Returns md5sum for a message object of type 'ArmJointAnglesGoal"
  "2b177ebe4b350b7b614560d610addf92")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ArmJointAnglesGoal>)))
  "Returns full string definition for message of type '<ArmJointAnglesGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%JointAngles angles~%~%================================================================================~%MSG: typepyt/JointAngles~%float32 hip~%float32 shoulder~%float32 elbow~%float32 wrist~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ArmJointAnglesGoal)))
  "Returns full string definition for message of type 'ArmJointAnglesGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%JointAngles angles~%~%================================================================================~%MSG: typepyt/JointAngles~%float32 hip~%float32 shoulder~%float32 elbow~%float32 wrist~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ArmJointAnglesGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'angles))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ArmJointAnglesGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ArmJointAnglesGoal
    (cl:cons ':angles (angles msg))
))
