// Generated by gencpp from file typepyt/JointAngles.msg
// DO NOT EDIT!


#ifndef TYPEPYT_MESSAGE_JOINTANGLES_H
#define TYPEPYT_MESSAGE_JOINTANGLES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace typepyt
{
template <class ContainerAllocator>
struct JointAngles_
{
  typedef JointAngles_<ContainerAllocator> Type;

  JointAngles_()
    : hip(0.0)
    , shoulder(0.0)
    , elbow(0.0)
    , wrist(0.0)  {
    }
  JointAngles_(const ContainerAllocator& _alloc)
    : hip(0.0)
    , shoulder(0.0)
    , elbow(0.0)
    , wrist(0.0)  {
  (void)_alloc;
    }



   typedef float _hip_type;
  _hip_type hip;

   typedef float _shoulder_type;
  _shoulder_type shoulder;

   typedef float _elbow_type;
  _elbow_type elbow;

   typedef float _wrist_type;
  _wrist_type wrist;




  typedef boost::shared_ptr< ::typepyt::JointAngles_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::typepyt::JointAngles_<ContainerAllocator> const> ConstPtr;

}; // struct JointAngles_

typedef ::typepyt::JointAngles_<std::allocator<void> > JointAngles;

typedef boost::shared_ptr< ::typepyt::JointAngles > JointAnglesPtr;
typedef boost::shared_ptr< ::typepyt::JointAngles const> JointAnglesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::typepyt::JointAngles_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::typepyt::JointAngles_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace typepyt

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'typepyt': ['/home/nvidia/Ty/TyPEpyt/ros_ws/src/typepyt/msg', '/home/nvidia/Ty/TyPEpyt/ros_ws/devel/share/typepyt/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::typepyt::JointAngles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::typepyt::JointAngles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::typepyt::JointAngles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::typepyt::JointAngles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::typepyt::JointAngles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::typepyt::JointAngles_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::typepyt::JointAngles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bc7aa8d1069f4ed465de7f6e207623f0";
  }

  static const char* value(const ::typepyt::JointAngles_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbc7aa8d1069f4ed4ULL;
  static const uint64_t static_value2 = 0x65de7f6e207623f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::typepyt::JointAngles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "typepyt/JointAngles";
  }

  static const char* value(const ::typepyt::JointAngles_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::typepyt::JointAngles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 hip\n\
float32 shoulder\n\
float32 elbow\n\
float32 wrist\n\
";
  }

  static const char* value(const ::typepyt::JointAngles_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::typepyt::JointAngles_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.hip);
      stream.next(m.shoulder);
      stream.next(m.elbow);
      stream.next(m.wrist);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointAngles_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::typepyt::JointAngles_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::typepyt::JointAngles_<ContainerAllocator>& v)
  {
    s << indent << "hip: ";
    Printer<float>::stream(s, indent + "  ", v.hip);
    s << indent << "shoulder: ";
    Printer<float>::stream(s, indent + "  ", v.shoulder);
    s << indent << "elbow: ";
    Printer<float>::stream(s, indent + "  ", v.elbow);
    s << indent << "wrist: ";
    Printer<float>::stream(s, indent + "  ", v.wrist);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TYPEPYT_MESSAGE_JOINTANGLES_H
